{% set name = "Dioptas" %}
{% set version = "0.4.1" %}
{% set sha256 = "5911464f2141f19720d8b987796d86344602737c9e4c34309d0b0dfd2b32d90b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dioptas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - dioptas = dioptas:main

requirements:
  build:
    - {{ compiler('fortran') }}  

  host:
    - python
    - pip
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - scipy
    - pyqt
    - pyqtgraph
    - lmfit
    - fabio
    - pyfai
    - pycifrw
    - future
    - scikit-image
    - qtpy

test:
  # Python imports
  imports:
    - dioptas

app:
  entry: dioptas
  type: desk
  summary: "Dioptas"
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL3
  license_family: GPL
  license_file: license.txt
  summary: 'Dioptas is a Python-based program for on-the-fly data processing 
  and exploration of two-dimensional X-ray diffraction area detector data. 
  It is specifically designed for the large amount of data collected at XRD 
  beamlines at synchrotrons. Its fast data reduction algorithm and graphical 
  data exploration capabilities make it ideal for online data processing during 
  XRD experiments and batch post-processing of large numbers of images.'

  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/Dioptas/Dioptas

extra:
  recipe-maintainers:
    - CPrescher
