{% set name = "dioptas" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dioptas-{{ version }}.tar.gz
  sha256: cb3019da250aada747ed024d7ed473ddc23be10b22aa996fd076656d5045ca23

build:
  entry_points:
    - dioptas = scripts:dioptas.main
    # Requires sharedmem dependency not available in conda-forge
    # - dioptas_batch = scripts:dioptas_batch.main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - cython
    - pip
  run:
    - python
    - cython
    - future
    - h5py
    - hdf5plugin
    - lmfit
    - pandas
    - psutil
    - pycifrw
    - python-dateutil
    - pyqt  # Use pyqt6 when available in conda-forge
    - pyfai >=2023.1.0
    - pyqtgraph
    - qtpy
    - scikit-image
    - watchdog
    - numpy
    - fabio
    - scipy
    # Optional dependency missing:
    # - extra-data
    # dioptas_batch dependency missing:
    # - sharedmem

test:
  imports:
    - dioptas

app:
  entry: dioptas
  summary: "Dioptas"
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL-3.0-or-later
  license_file: license.txt
  summary: GUI program for reduction and exploration of 2D X-ray diffraction data
  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/dioptas/dioptas

extra:
  recipe-maintainers:
    - CPrescher
    - t20100
