{% set name = "dioptas" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dioptas-{{ version }}.tar.gz
  sha256: 21b9d85a7bafdebf0c9d0bbcd8c2dfd45543362fa26b50095f261f5a66bb3e47

build:
  noarch: python
  entry_points:
    - dioptas = dioptas:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
    - poetry-dynamic-versioning
  run:
    - python >=3.8
    - h5py
    - hdf5plugin
    - lmfit
    - pandas
    - psutil
    - pycifrw
    - pyqt  # Use pyqt6 when available in conda-forge
    - pyfai ~=2023.5
    - pyqtgraph
      pyshortcuts
    - qtpy
    - scikit-image
    - watchdog
    - pyopengl
    - xypattern
    - numpy
    - scipy
    - numexpr
    - qt-material
    # Optional dependency missing:
    # - extra-data
    # - pyopengl-accelerate
    # dioptas_batch dependency missing:
    # - sharedmem

test:
  imports:
    - dioptas

app:
  entry: dioptas
  summary: "Dioptas"
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL-3.0-or-later
  license_file: license.txt
  summary: GUI program for reduction and exploration of 2D X-ray diffraction data
  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/dioptas/dioptas

extra:
  recipe-maintainers:
    - CPrescher
    - t20100
