{% set name = "dioptas" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dioptas-{{ version }}.tar.gz
  sha256: 2f3b2c5ac9a70b0bf746c42a5cf6b41b1e1ea34c39d1f77ae6956409064081c3

build:
  skip: true  # [py<39]
  entry_points:
    - dioptas = scripts:dioptas.main
    # Requires sharedmem dependency not available in conda-forge
    # - dioptas_batch = scripts:dioptas_batch.main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - poetry-core
    - cython
    - setuptools
    - poetry-dynamic-versioning
  run:
    - python
    - future
    - h5py
    - hdf5plugin
    - lmfit
    - pandas
    - psutil
    - pycifrw
    - pyqt  # Use pyqt6 when available in conda-forge
    - pyfai >=2023.5.0
    - pyqtgraph
    - qtpy
    - scikit-image
    - watchdog
    - pyopengl
    - numpy
    - scipy
    - numexpr
    # Optional dependency missing:
    # - extra-data
    # - pyopengl-accelerate
    # - xypattern
    # dioptas_batch dependency missing:
    # - sharedmem

test:
  imports:
    - dioptas

app:
  entry: dioptas
  summary: "Dioptas"
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL-3.0-or-later
  license_file: license.txt
  summary: GUI program for reduction and exploration of 2D X-ray diffraction data
  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/dioptas/dioptas

extra:
  recipe-maintainers:
    - CPrescher
    - t20100
