{% set version = "0.5.0" %}

package:
  name: dioptas
  version: {{ version }}

source:
  url: https://github.com/Dioptas/Dioptas/archive/{{ version }}.tar.gz
  sha256: 207e8fe08507171aa8e7c26fd705cf36f383e0acacf300b42a00f1273f7d4f44

build:
  number: 0
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dioptas = dioptas:main

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - scipy
    - pyqt
    - pyqtgraph
    - lmfit
    - fabio
    - pyfai
    - pycifrw
    - future
    - scikit-image
    - qtpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyqt
    - pyqtgraph
    - lmfit
    - fabio
    - pyfai
    - pycifrw
    - future
    - scikit-image
    - qtpy

test:
  imports:
    - dioptas

app:
  entry: dioptas
  type: desk
  summary: Dioptas
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL-3.0
  license_family: GPL
  license_file: license.txt
  summary: The silx project aims at providing a collection of Python packages to support the development of data assessment, reduction and analysis applications at synchrotron radiation facilities.
  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/Dioptas/Dioptas

extra:
  recipe-maintainers:
    - CPrescher
