{% set name = "Dioptas" %}
{% set version = "0.5.0" %}
{% set sha256 = "3333bf1f6c3c31294c8a8d6294c9232796d0f53e24095c2304ab76ca5bd9514e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Dioptas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py27]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - dioptas = dioptas:main

requirements:
  build:
    - {{ compiler('fortran') }}  
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.11
    - scipy
    - pyqt
    - pyqtgraph
    - lmfit
    - fabio
    - pyfai
    - pycifrw
    - future
    - scikit-image
    - qtpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyqt
    - pyqtgraph
    - lmfit
    - fabio
    - pyfai
    - pycifrw
    - future
    - scikit-image
    - qtpy

test:
  # Python imports
  imports:
    - dioptas

app:
  entry: dioptas
  type: desk
  summary: "Dioptas"
  icon: icon.png

about:
  home: https://github.com/Dioptas/Dioptas
  license: GPL3
  license_family: GPL
  license_file: license.txt
  summary: 'The silx project aims at providing a collection of Python packages
  to support the development of data assessment, reduction and analysis
  applications at synchrotron radiation facilities.'

  doc_url: https://dioptas.readthedocs.io/en/stable/
  dev_url: https://github.com/Dioptas/Dioptas

extra:
  recipe-maintainers:
    - CPrescher
