# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JUWeCB/ifHaN69YJpZL8zoVnh5IFQnUEjBw9GYShHVkv4qlHjqh1RIvybIcSGcjDx50hdQY7BkJq5uZ2xgQw+Qi7qMn+S99dEQ0cwURmeP3qi4zgMkp9SJFDO98G5jdax952b3D8D+dxTK5Ly4So+NJHpvKzobOOUJkUI2H5VnGJwix7BDCRwP/dbjOGpPktvRyg3S22sefhLRLMkzq6p+E//eFXUfYuW5W3JyBZTpUNXcmRnl7yw37MIZqlmMiOCl499ol1X2adxRQ7FHiwriOzhfWUZrHpIqcO/Nr4ghhAu9qn4janMg7SgAa7D/qrcRSyKtlBrA+38CDrwXN0nT4o8djkVg9Ee6i2Whf8CwrCuwdJJyj6i0KZjG1lr8d4uxxyFuHeQi+FYv0vcZFQXKjENVHp64/N1aKqpyAF6BbYyRL2GhPGkS3B/G6N7mrlP6zLrTslP2BqefaNvbDjrPok6abhW5wFEGD6lN3B6WWliodAmVnEeFdVI+Z3pD+t4R3lWpktam7o5KoqcA8jd9r8npF0L00MuO9nMFwPvOUK5Xj9XBiCPRIQWb8Ttfn941QaqOunoHALRmvNqEk0gRhVpLABhRz5MvfvSvZgmCJ4EQrCyK80hOp82iThZTohE5GipCVWELKuJnGU9rTuTnYGbnaErgj5F4pqKJqaU0Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
